"""Low-code → code: generate a standalone, editable mlx-tune training script
that reproduces exactly what the GUI is configured to do."""

from __future__ import annotations

from .registry import get_task
from .training import RunConfig, build_trainer_args


def _fmt(v) -> str:
    return repr(v)


def generate_script(cfg: RunConfig, dataset_source: str = "",
                    dataset_is_local: bool = False) -> str:
    spec = get_task(cfg.task)
    args = build_trainer_args(cfg)
    args_body = ",\n        ".join(f"{k}={_fmt(v)}" for k, v in args.items())

    imports = {spec.trainer}
    if spec.config_module == "mlx_tune":
        imports.add(spec.config)
    if spec.collator:
        imports.add(spec.collator)
    import_line = f"from mlx_tune import {spec.loader}, {', '.join(sorted(imports))}"
    extra_import = ""
    if spec.config_module != "mlx_tune":
        extra_import = f"\nfrom {spec.config_module} import {spec.config}"

    # --- model loading -------------------------------------------------------
    load_kwargs = ""
    if spec.modality == "text":
        load_kwargs = (f",\n    max_seq_length={cfg.max_seq_length},"
                       f"\n    load_in_4bit={cfg.load_in_4bit},")
    handle = "processor" if spec.modality in ("vision", "image") else "tokenizer"

    # --- LoRA ------------------------------------------------------------------
    lora_block = ""
    if cfg.use_lora and spec.peft_supported:
        tm = ""
        if spec.modality == "text":
            tm = f"\n    target_modules={cfg.target_modules!r},"
        lora_block = f"""
# --- 2. Attach LoRA adapters -------------------------------------------------
model = {spec.loader}.get_peft_model(
    model,
    r={cfg.lora_r},
    lora_alpha={cfg.lora_alpha},{tm}
)
"""

    # --- dataset ------------------------------------------------------------------
    if dataset_is_local:
        ds_block = f"""import json

with open({dataset_source!r}) as f:
    train_dataset = [json.loads(line) for line in f if line.strip()]"""
    elif dataset_source:
        ds_block = f"""from datasets import load_dataset

train_dataset = load_dataset({dataset_source!r}, split="train")"""
    else:
        ds_block = """train_dataset = [
    # TODO: fill with rows shaped like: %s
]""" % (dict.fromkeys(spec.dataset_schema, "..."),)

    collator_line = ""
    if spec.collator:
        collator_line = f"\n    data_collator={spec.collator}(model, {handle}),"

    return f'''"""Auto-generated by Finetuner Studio — https://github.com/aykutcayir34/finetuner

Task    : {spec.label}
Backend : mlx-tune (https://github.com/ARahim3/mlx-tune)

This script is fully standalone: edit it, version it, or move it to a cloud
GPU box — the mlx-tune API is Unsloth-compatible by design.
"""

{import_line}{extra_import}

# --- 1. Load the base model ----------------------------------------------------
model, {handle} = {spec.loader}.from_pretrained(
    {cfg.model_name!r}{load_kwargs}
)
{lora_block}
# --- 3. Dataset ------------------------------------------------------------------
{ds_block}

# --- 4. Train ----------------------------------------------------------------------
trainer = {spec.trainer}(
    model=model,
    {handle}={handle},
    train_dataset=train_dataset,{collator_line}
    args={spec.config}(
        {args_body},
    ),
)
trainer.train()

# --- 5. Save -----------------------------------------------------------------------
model.save_pretrained("lora_model")                      # adapters only
# model.save_pretrained_merged("merged", {handle})       # merged fp16 model
# model.push_to_hub("your-username/your-model")          # upload to the Hub
'''
